version: '4'
services:
  my-pj-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./src:/project/src
      - ./angular.json:/project/angular.json
      - ./tsconfig.json:/project/tsconfig.json
    environment:
      - NODE_ENV=development